apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: voting
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      role: db
      app: db
  template:
    metadata:
      labels:
        role: db
        app: db
        env: demo
        replicaset: rs0.main
    spec:
      containers:
        - name: mongo
          image: mongo:4.2
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
