apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: voting
  labels:
    role: db
    env: demo
    app: db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: db
    app: db
